### ISSUE TITLE
Add AppChecker to the list

### ISSUE THREAD

**Issue by AppChecker** [exakat/php-static-analysis-tools#10]
Hello!

Echelon Team has developed [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php) PHP static analyzer. AppChecker finds bugs, defects and vulnerabilities in source code.

Here are some examples of bugs detection:
https://github.com/magento/magento2/issues/6320
https://github.com/magento/magento2/issues/7776
https://github.com/magento/magento2/issues/6715
https://github.com/zendframework/zf1/issues/716
https://github.com/LiveHelperChat/livehelperchat/issues/893
https://github.com/contao/core/issues/8422
https://github.com/b2evolution/b2evolution/issues/30
https://github.com/Dolibarr/dolibarr/issues/5479
https://github.com/kajona/kajonacms/issues/98
https://github.com/exponentcms/exponent-cms/issues/66

**Comment by exakat** [comment]
Added.

**Comment by AppChecker** [comment]
Hello!

Thank you for adding AppChecker! But we want to make some remarks:
1. AppChecker is not actually a SaaS, I guess that better it would be in Bugs Finders
2. Please add some description (static analysis tool for finding bugs, weaknesses and vulnerabilities in source code)
