### ISSUE TITLE
Remove some duplicates

### ISSUE THREAD

**Issue by MetalArend** [exakat/php-static-analysis-tools#15]
PHP Analysis is both in "Bugs finders" and "Misc"
PHP semver is twice in "Metrics"
RIPS is both in "Bugs finders" and "SaaS"

**Comment by TomasVotruba** [comment]
Could you send PR?

**Comment by MetalArend** [comment]
@TomasVotruba There you go.

**Comment by TomasVotruba** [comment]
@MetalArend Thank you!
