### ISSUE TITLE
Exakat is failing the install

### ISSUE THREAD

**Issue by chogberg** [exakat/php-static-analysis-tools#45]
Hi,

When trying to install Exakat I use the following procedure:

1. mkdir exakat
2. cd exakat
3. curl -o exakat.phar 'https://www.exakat.io/versions/index.php?file=latest'
4. php exakat.phar install

`Warning: file_get_contents(https://www.exakat.io/versions/apache-tinkerpop-gremlin-server-3.4.12-bin.zip.sha256): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 in phar:///Volumes/dev/exakat/exakat.phar/library/Exakat/Tasks/Install.php on line 59`

Which results in a failing install:

`Fatal error: Uncaught TypeError: substr() expects parameter 1 to be string, bool given in phar:///Volumes/dev/exakat/exakat.phar/library/Exakat/Tasks/Install.php:59
Stack trace:
#0 phar:///Volumes/dev/exakat/exakat.phar/library/Exakat/Tasks/Install.php(59): substr(false, 0, 64)
#1 phar:///Volumes/dev/exakat/exakat.phar/library/Exakat/Exakat.php(196): Exakat\Tasks\Install->run()
#2 phar:///Volumes/dev/exakat/exakat.phar/exakat(52): Exakat\Exakat->execute()
#3 /Volumes/dev/exakat/exakat.phar(10): include('phar:///Volumes...')
#4 {main}
  thrown in phar:///Volumes/dev/exakat/exakat.phar/library/Exakat/Tasks/Install.php on line 59`

**Comment by AJenbo** [comment]
Looks like the wrong repo, try here instead: https://github.com/exakat/exakat
